# name: Golden AMI CI

# on:
#     push:
#         branches:
#             - main
#     # pull_request:
#     #     branches:
#     #         - main

# permissions:
#     id-token: write
#     contents: read
    

# jobs:
#     validate-components:
#         name: Validate AWSTOE Components
#         runs-on: ubuntu-latest

#         steps:
#             - name: Checkout Repository
#               uses: actions/checkout@v5
            
#             # - name: Debug OIDC
#             #   uses: github/actions-oidc-debugger@main
#             #   with:
#             #     audience: sts.amazonaws.com

#             - name: Configure AWS credentials using OIDC
#               uses: aws-actions/configure-aws-credentials@v5
#               with:
#                 role-to-assume: ${{ vars.AWS_ROLE_ARN }}
#                 aws-region: ${{ vars.AWS_REGION }}

#             - name: Verify AWS Identity
#               run: |
#                 aws sts get-caller-identity

#             - name: Install AWSTOE
#               run: |
#                 set -e
#                 echo "Installing AWSTOE..."
#                 curl -fL \
#                     https://awstoe-us-east-1.s3.us-east-1.amazonaws.com/latest/linux/amd64/awstoe \
#                     -o awstoe
#                 chmod +x awstoe
#                 sudo mv awstoe /usr/local/bin/awstoe
#                 echo "AWSTOE installation completed successfully."
#                 awstoe version

#             - name: Validate AWSTOE Component files
#               run: |  
#                 set -e
#                 echo "Validating AWSTOE component files..."

#                 for file in components/*/component.yml; do
#                     echo "Checking $file..."
#                     awstoe validate --documents "$file"
#                 done

#                 echo "All AWSTOE component files validated successfully."

# TESSTING>>>>>>>>>>>>>>>>>>

name: List EC2 Instances

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  list-ec2:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Configure AWS credentials using OIDC
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ vars.AWS_ROLE_ARN }}
        aws-region: ${{ vars.AWS_REGION }}

    - name: List EC2 Instances
      run: |
        aws ec2 describe-instances \
          --query "Reservations[*].Instances[*].InstanceId" \
          --output table